# Generated by Django 4.1.3 on 2022-11-14 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orde_name',
            new_name='order_name',
        ),
    ]
